music_app/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands 
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true
    
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :email, uniqueness: true
    validates :password, length: { minimum: 6} , allow_nil: true
    
    after_initialize :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil unless user && user.is_password?(password)
        user
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        bcrypt = BCrypt::Password.new(self.password_digest)
        bcrypt.is_password?(password)
    end

    def reset_session_token!
        self.update!(session_token: self.class.generate_session_token)
        self.session_token
    end

    private
    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #c-e-l-l-l
    helper_method :current_user, :logged_in?, :login!

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end
    
    def logout!
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find_by(id: params[:id])

        if @band
            render :show
        else
            redirect_to bands_url
        end
    end

    def new
        @band = Band.new
        render :new
    end
    
    
    def edit
        @band = Band.find(params[:id])
        render :edit
    end
    

    def create
        @band = Band.new(band_params)

        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end
    
    def update
        @band = Band.find(params[:id])

        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email],
                                        params[:user][:password])
        if user
            login!(user)
            redirect_to user_url(user)
        else
            flash.now[:errors] = ['Invalid Email or Password']
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        render :show
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end


    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/bands/edit.html.erb
<h1>Edit a Band</h1>
<form action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="name">Band Name
    </label>
    <input type="text" name="band[name]" id="name" value= "<%= @band.name %>">
    <input class="button" type="submit" value="Edit Band!">
</form>

music_app/app/views/bands/index.html.erb
<h1>All Bands!</h1>
    <ul>
        <% @bands.each do |band|%>
            <li><%= band.name %></li>
            <a class="band" href="<%=  band_url(band) %>">Take a look!</a><br><br>
        <% end %>
    </ul>


 <a class="band" href="<%=  new_band_url %>">Add a New Band!</a><br><br>

music_app/app/views/bands/new.html.erb
<h1>Add a New Band</h1>
<form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="name">Band Name
    </label>
    <input type="text" name="band[name]" id="name" value= "<%= @band.name %>">
    <input class="button" type="submit" value="Submit Band!">
</form>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<a class="button" href="<%=  edit_band_url(@band) %>">Edit This Band!</a><br><br>
<form action="<%= band_url %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input class="button" type="submit" value= "Delete This Band :(">
</form>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <% if logged_in? %>
    <h1>Music App</h1>
    <h3>Hello, <%= current_user.email %></h3>
    <div class="f">
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input class = "form-submit-button" type="submit" value="Log Out!">
      </form>
    </div>
   
  <% else %>
    <h1>Music App</h1>
    <div>
      <a class="link" href="<%= new_user_url %>">Sign Up!</a>
      <a class="link" href="<%= new_session_url %>">Log In!</a>
    </div>
  <% end %>
  </header>
  <% if flash[:errors] %>
  <ul>
   <% flash[:errors].each do |error| %>
    <li><%= error %></li>
   <% end %>
  </ul>
   <% end %>
    <a class="band" href="<%=  bands_url %>">All Bands!</a><br><br>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h2>Sign Up!</h2>
<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="email">Email
    </label>
    <input type="text" id="email" name="user[email]" value="<%= @user.email %>">

    <label for="password">Password
    </label>
    <input type="password" id="password" name="user[password]" value="">

    <input class="button" type="submit" value="Sign Up!">
</form>

music_app/app/views/users/show.html.erb
<h2>MUSIC</h2>